package homework.homework_7_JDI.enums;

public enum JDI_SITE_PAGES {
    HOME, CONTACT_FORM, METALS_COLORS, SERVICE, SUPPORT, DATES, COMPLEX_TABLE, SIMPLE_TABLE, TABLE_WITH_PAGES, DIFFERENT_ELEMENTS
}
